<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@include file="../../common/header.jsp" %>

<div class="mb-4">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <h2 class="fw-bold">📱 Chi tiết Mã QR</h2>
            <p class="text-muted">Thông tin chi tiết về mã QR và lô sản xuất</p>
        </div>
        <a href="${pageContext.request.contextPath}/traceability?action=result&qrId=${qrCode.id}" 
           class="btn btn-success">🔍 Xem Truy xuất</a>
    </div>
</div>

<div class="row">
    <div class="col-md-5">
        <div class="card shadow-sm border-0 mb-4">
            <div class="card-body text-center py-4">
                <!-- QR Code Image - Generated by ZXing -->
                <div class="qr-code-container mb-3 p-3 bg-white d-inline-block border rounded">
                    <img src="${pageContext.request.contextPath}/qr-image?id=${qrCode.id}" 
                         alt="QR Code: ${qrCode.qrValue}"
                         width="250" height="250"
                         class="img-fluid"
                         id="qrCodeImage"
                         style="image-rendering: pixelated;">
                </div>
                <hr>
                <h5 class="text-success fw-bold mb-2">${qrCode.qrValue}</h5>
                <div class="mt-2">
                    <c:choose>
                        <c:when test="${qrCode.status == 'CREATED'}">
                            <span class="badge bg-success fs-6">Đã tạo</span>
                        </c:when>
                        <c:when test="${qrCode.status == 'PRINTED'}">
                            <span class="badge bg-info fs-6">Đã in</span>
                        </c:when>
                        <c:when test="${qrCode.status == 'USED'}">
                            <span class="badge bg-warning fs-6">Đã dùng</span>
                        </c:when>
                        <c:otherwise>
                            <span class="badge bg-secondary fs-6">${qrCode.status}</span>
                        </c:otherwise>
                    </c:choose>
                </div>
                <div class="text-muted mt-2">
                    <small>Ngày tạo: <fmt:formatDate value="${qrCode.createdAt}" pattern="dd/MM/yyyy HH:mm"/></small>
                </div>
                <div class="mt-3 d-flex gap-2 justify-content-center">
                    <button class="btn btn-outline-primary" onclick="window.print()">
                        <i class="bi bi-printer me-1"></i> In mã QR
                    </button>
                    <a href="${pageContext.request.contextPath}/qr-image?id=${qrCode.id}" 
                       download="QR_${qrCode.qrValue}.png"
                       class="btn btn-outline-success">
                        <i class="bi bi-download me-1"></i> Tải xuống
                    </a>
                </div>
            </div>
        </div>
        
        <!-- Scan Instructions -->
        <div class="card shadow-sm border-0 bg-light">
            <div class="card-body">
                <h6 class="fw-bold mb-2"><i class="bi bi-phone me-2"></i>Hướng dẫn quét</h6>
                <ol class="small mb-0 ps-3">
                    <li>Mở ứng dụng Camera hoặc quét QR trên điện thoại</li>
                    <li>Hướng camera vào mã QR ở trên</li>
                    <li>Nhấn vào link hiện ra để xem thông tin truy xuất</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="col-md-7">
        <h5 class="fw-bold mb-3">📋 Thông tin liên kết</h5>
        
        <c:if test="${not empty batch}">
            <div class="card shadow-sm border-0 mb-3">
                <div class="card-header bg-light">
                    <h6 class="mb-0 fw-bold">📦 Lô sản xuất</h6>
                </div>
                <div class="card-body">
                    <p class="mb-1">
                        <strong>Mã lô:</strong> 
                        <a href="${pageContext.request.contextPath}/production-batches?action=view&id=${batch.id}">
                            ${batch.batchCode}
                        </a>
                    </p>
                    <p class="mb-1"><strong>Sản lượng:</strong> ${batch.totalQuantity} ${batch.unit}</p>
                    <p class="mb-1"><strong>Ngày thu hoạch:</strong> <fmt:formatDate value="${batch.harvestDate}" pattern="dd/MM/yyyy"/></p>
                    <c:if test="${not empty batch.expiryDate}">
                        <p class="mb-0"><strong>Hạn sử dụng:</strong> <fmt:formatDate value="${batch.expiryDate}" pattern="dd/MM/yyyy"/></p>
                    </c:if>
                </div>
            </div>
        </c:if>

        <c:if test="${not empty product}">
            <div class="card shadow-sm border-0 mb-3">
                <div class="card-header bg-light">
                    <h6 class="mb-0 fw-bold">🌾 Nông sản</h6>
                </div>
                <div class="card-body">
                    <p class="mb-1"><strong>Tên:</strong> ${product.name}</p>
                    <p class="mb-0"><strong>Đơn vị:</strong> ${product.unit}</p>
                </div>
            </div>
        </c:if>

        <c:if test="${not empty member}">
            <div class="card shadow-sm border-0 mb-3">
                <div class="card-header bg-light">
                    <h6 class="mb-0 fw-bold">👤 Thành viên sản xuất</h6>
                </div>
                <div class="card-body">
                    <p class="mb-1"><strong>Họ tên:</strong> ${member.full_name}</p>
                    <c:if test="${not empty member.phone}">
                        <p class="mb-1"><strong>Điện thoại:</strong> ${member.phone}</p>
                    </c:if>
                    <c:if test="${not empty member.address}">
                        <p class="mb-0"><strong>Địa chỉ:</strong> ${member.address}</p>
                    </c:if>
                </div>
            </div>
        </c:if>
    </div>
</div>

<div class="mt-3">
    <a href="${pageContext.request.contextPath}/qr-codes" class="btn btn-secondary">
        ← Quay lại danh sách
    </a>
</div>

<%@include file="../../common/footer.jsp" %>
